import type { AppProps } from 'next/app';
import { SessionProvider } from "next-auth/react";
import { ReactElement, ReactNode } from 'react';
import DefaultLayout from '@/components/Layouts/DefaultLayout';
import { Provider } from 'react-redux';
import store from '../store/index';
import Head from 'next/head';
import { NextPage } from 'next';
import { appWithI18Next } from 'ni18n';
import { ni18nConfig } from '@/ni18n.config.ts';
import "@/styles/globals.css";

export type NextPageWithLayout<P = {}, IP = P> = NextPage<P, IP> & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

const App = ({ Component, pageProps: { session, ...pageProps } }: AppPropsWithLayout) => {
  const getLayout = Component.getLayout ?? ((page) => <DefaultLayout>{page}</DefaultLayout>);

  return (
    <Provider store={store}>
      <SessionProvider session={session}>
        <Head>
          <title>
            Drive Ogan Ilir
          </title>
          <meta charSet="UTF-8" />
          <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.png" />
          <meta name="robots" content="index, follow" />
          <meta name="googlebot" content="index, follow" />

          <style>
            {`
            .grecaptcha-badge 
            {
              position: relative !important;
              left: 0px !important;
              top: 0px !important;
            }
        `}
          </style>
        </Head>

        {getLayout(<Component {...pageProps} />)}

      </SessionProvider>
    </Provider>
  );
};

export default appWithI18Next(App, ni18nConfig);